export interface BibleBook {
  en: string;
  zh: string;
  chapters: number;
}

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { en: "Genesis", zh: "創世記", chapters: 50 },
  { en: "Exodus", zh: "出埃及記", chapters: 40 },
  { en: "Leviticus", zh: "利未記", chapters: 27 },
  { en: "Numbers", zh: "民數記", chapters: 36 },
  { en: "Deuteronomy", zh: "申命記", chapters: 34 },
  { en: "Joshua", zh: "約書亞記", chapters: 24 },
  { en: "Judges", zh: "士師記", chapters: 21 },
  { en: "Ruth", zh: "路得記", chapters: 4 },
  { en: "1 Samuel", zh: "撒母耳記上", chapters: 31 },
  { en: "2 Samuel", zh: "撒母耳記下", chapters: 24 },
  { en: "1 Kings", zh: "列王紀上", chapters: 22 },
  { en: "2 Kings", zh: "列王紀下", chapters: 25 },
  { en: "1 Chronicles", zh: "歷代志上", chapters: 29 },
  { en: "2 Chronicles", zh: "歷代志下", chapters: 36 },
  { en: "Ezra", zh: "以斯拉記", chapters: 10 },
  { en: "Nehemiah", zh: "尼希米記", chapters: 13 },
  { en: "Esther", zh: "以斯帖記", chapters: 10 },
  { en: "Job", zh: "約伯記", chapters: 42 },
  { en: "Psalm", zh: "詩篇", chapters: 150 },
  { en: "Proverbs", zh: "箴言", chapters: 31 },
  { en: "Ecclesiastes", zh: "傳道書", chapters: 12 },
  { en: "Song of Songs", zh: "雅歌", chapters: 8 },
  { en: "Isaiah", zh: "以賽亞書", chapters: 66 },
  { en: "Jeremiah", zh: "耶利米書", chapters: 52 },
  { en: "Lamentations", zh: "耶利米哀歌", chapters: 5 },
  { en: "Ezekiel", zh: "以西結書", chapters: 48 },
  { en: "Daniel", zh: "但以理書", chapters: 12 },
  { en: "Hosea", zh: "何西阿書", chapters: 14 },
  { en: "Joel", zh: "約珥書", chapters: 3 },
  { en: "Amos", zh: "阿摩司書", chapters: 9 },
  { en: "Obadiah", zh: "俄巴底亞書", chapters: 1 },
  { en: "Jonah", zh: "約拿書", chapters: 4 },
  { en: "Micah", zh: "彌迦書", chapters: 7 },
  { en: "Nahum", zh: "那鴻書", chapters: 3 },
  { en: "Habakkuk", zh: "哈巴谷書", chapters: 3 },
  { en: "Zephaniah", zh: "西番雅書", chapters: 3 },
  { en: "Haggai", zh: "哈該書", chapters: 2 },
  { en: "Zechariah", zh: "撒迦利亞書", chapters: 14 },
  { en: "Malachi", zh: "瑪拉基書", chapters: 4 },
  // New Testament
  { en: "Matthew", zh: "馬太福音", chapters: 28 },
  { en: "Mark", zh: "馬可福音", chapters: 16 },
  { en: "Luke", zh: "路加福音", chapters: 24 },
  { en: "John", zh: "約翰福音", chapters: 21 },
  { en: "Acts", zh: "使徒行傳", chapters: 28 },
  { en: "Romans", zh: "羅馬書", chapters: 16 },
  { en: "1 Corinthians", zh: "哥林多前書", chapters: 16 },
  { en: "2 Corinthians", zh: "哥林多後書", chapters: 13 },
  { en: "Galatians", zh: "加拉太書", chapters: 6 },
  { en: "Ephesians", zh: "以弗所書", chapters: 6 },
  { en: "Philippians", zh: "腓立比書", chapters: 4 },
  { en: "Colossians", zh: "歌羅西書", chapters: 4 },
  { en: "1 Thessalonians", zh: "帖撒羅尼迦前書", chapters: 5 },
  { en: "2 Thessalonians", zh: "帖撒羅尼迦後書", chapters: 3 },
  { en: "1 Timothy", zh: "提摩太前書", chapters: 6 },
  { en: "2 Timothy", zh: "提摩太後書", chapters: 4 },
  { en: "Titus", zh: "提多書", chapters: 3 },
  { en: "Philemon", zh: "腓利門書", chapters: 1 },
  { en: "Hebrews", zh: "希伯來書", chapters: 13 },
  { en: "James", zh: "雅各書", chapters: 5 },
  { en: "1 Peter", zh: "彼得前書", chapters: 5 },
  { en: "2 Peter", zh: "彼得後書", chapters: 3 },
  { en: "1 John", zh: "約翰一書", chapters: 5 },
  { en: "2 John", zh: "約翰二書", chapters: 1 },
  { en: "3 John", zh: "約翰三書", chapters: 1 },
  { en: "Jude", zh: "猶大書", chapters: 1 },
  { en: "Revelation", zh: "啟示錄", chapters: 22 },
];